### ISSUE TITLE
Readability: Intro & Executive Summary 

### ISSUE THREAD

**Issue by buchananwp** [Green-Software-Foundation/software_carbon_intensity#116]
- [x] Intro & executive summary
- [ ] 1. bump the 'core characteristics' section to the top for readability
- [ ] 2.Incorporate comments from ['getting started' discussion](https://github.com/Green-Software-Foundation/software_carbon_intensity/discussions/115) with core characteristics section in the spec
- [ ] simplified SCI equation at the front (similar to the slide deck that Asim showed)
- [x] references/dictionary at the bottom 
- [x] delete empty 'boundaries' section

**Comment by atg-abhishek** [comment]
@buchananwp @jawache @Henry-WattTime do we want to address all of the 6 items above for v1?

**Comment by atg-abhishek** [comment]
@jawache for the outstanding items, please feel free to hit the button to branch them off into new issues, thanks!
