### ISSUE TITLE
Improve phrasing of problem statement

### ISSUE THREAD

**Issue by dschien** [Green-Software-Foundation/software_carbon_intensity#129]
The phrasing is vague in many places and needs clarity prior to release for public consumption. Example:
"The purpose of this specification will be to enable standardization across industry empowering individuals and organizations to make more informed choices in the software solutions that they pick. " - "more informed choices in the software solutions that they pick" - what kind of choices are these? What software solutions are meant here?

**Comment by atg-abhishek** [comment]
@dschien there is a readability PR being made now that addresses a lot of this. See #121. Maybe you can add in your comments there on this? Thanks!
