### ISSUE TITLE
Conflicting use of I in `O = E * I`

### ISSUE THREAD

**Issue by dschien** [Green-Software-Foundation/software_carbon_intensity#141]
If `I` is defined as Location-based marginal carbon emissions - in a unit of mass of GHG. 

In `O = E * I` it is used as an intensity - as mass of GHG per electric energy.

I suppose the definition of `I` is wrong.
--- 
O = E * I = Operational emissions based on energy consumption (E) and location-based carbon intensity measurement (I)

**Comment by atg-abhishek** [comment]
Closing this issue since the updated SCI text has this addressed
