### ISSUE TITLE
Unclear `R` results in unclear definition `CI = C / R`

### ISSUE THREAD

**Issue by dschien** [Green-Software-Foundation/software_carbon_intensity#145]
In "R = Baseline as a denominator (e.g. carbon per additional user, API-call, ML job, etc)" - What is meant with carbon per additional API call? What is "carbon" here? "Carbon emissions?" This is very poor phrasing.
Let's assume it's unit is mass of GHG per dimension of the reference unit. 

Moreover, C is defined as "`C = O + M` = Total amount of carbon the software is emitting over a time period". This is also poorly phrased. However, I assume this is also supposed to have a unit of mass of GHG.

Thus,  `CI = C / R` has the dimensional unit of the reference unit.

It is very unclear what the purpose of this  "Total carbon intensity rate per baseline"  is supposed to be.

Would a concrete example help? Let's assume R is based on data transfer. E.g.
`R = 1gCO2e/bit`
Let's assume C is `1gCO2e`.
Then `CI = 1bit`.

What does this mean?

**Comment by atg-abhishek** [comment]
addressed in #121 but maybe some more food for thought @jawache ?
