### ISSUE TITLE
Normalize the use of various terms from RFC 2119 across the SCI 

### ISSUE THREAD

**Issue by atg-abhishek** [Green-Software-Foundation/software_carbon_intensity#159]
We want to make sure that the usage of terms coming from [RFC 2119](https://datatracker.ietf.org/doc/html/rfc2119) are used consistently for easier readability across the SCI. 

> **MUST** This word, or the terms "REQUIRED" or "SHALL", mean that the definition is an absolute requirement of the specification.

**Comment by Henry-WattTime** [comment]
Sara did a review, closing this
