### ISSUE TITLE
Change from R from "Baseline" to "Functional Unit"

### ISSUE THREAD

**Issue by SaraEmilyBergman** [Green-Software-Foundation/software_carbon_intensity#164]
Whenever the specification mentions "baseline", change it to "functional unit" for R.

**Comment by atg-abhishek** [comment]
@SaraEmilyBergman will you be creating a PR for this?

**Comment by SaraEmilyBergman** [comment]
I was just asked in a meeting to create the Issue so we did not forget. I can't make next Thursday meeting but if it is ok to merge it when I'm not there I can do it?

**Comment by SaraEmilyBergman** [comment]
Okay it was a one-line change. I think you can merge without me present, here is the PR: https://github.com/Green-Software-Foundation/software_carbon_intensity/pull/170

**Comment by atg-abhishek** [comment]
Awesome thank you @SaraEmilyBergman - we have a meeting today as well (short one) so @seanmcilroy29 if we can add this to the agenda as well that would be great. I've reviewed and approved the PR.
