### ISSUE TITLE
Check the scope of the SCI to follow guidelines

### ISSUE THREAD

**Issue by atg-abhishek** [Green-Software-Foundation/software_carbon_intensity#171]
The Scope is a mandatory clause which describes what the document does (“specifies”, “establishes”, “gives 
guidelines for”, “defines terms”). It shall be worded as a series of statements of fact. It shall not contain requirements 
(“shall”), recommendations (“should”) or permissions (“may”).
The Scope shall be succinct so that it can be used as an abstract for bibliographic purposes (e.g. it is used on the ISO 
website). It shall explain the applicability of the document (and, if necessary, cases where it is not applicable).
For further information on the Scope, see ISO/IEC Directives, Part 2, 2016, Clause 14

**Comment by Sealjay** [comment]
> This document, the Software Carbon Intensity technical specification, describes a methodology for calculating the rate of carbon emissions for a software system. The purpose is to help users and developers make informed choices about which tools, approaches, architectures, and services they use in the future.

I think the scope is good as-is - I like it, but up for other changes that remain as succint if we want to clarify text.

**Comment by Henry-WattTime** [comment]
Looks good to working group.
