### ISSUE TITLE
[Consistency review] Software Carbon Intensity (SCI) Specification

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/software_carbon_intensity#175]
Consistency Review - In this phase, the Software Carbon Intensity (SCI) developed by the WG will be formally reviewed by all the GSF members. After this period, the Working Group will address any submitted issues received prior to formally Approving it for public release.

Submission for review - https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/dev/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md

Comments to be submitted in this issue or as a PR against the dev branch.

NOTE: **All** comments **must be** submitted by the next Standards WG meeting on 11th Nov @ 1630 UTC

**Comment by Henry-WattTime** [comment]
Consistency review closed, no further comments.
