### ISSUE TITLE
Provide Exemplary Case Studies 

### ISSUE THREAD

**Issue by Green-Software** [Green-Software-Foundation/software_carbon_intensity#177]
After we release the alpha version of SCI, the community may still need more guidelines on how to apply it to their software products. 

We may work together to come up with several exemplary case studies to help the community better understand how to leverage SCI to reduce the carbon emissions of their software.  

We can also consider publish the updated version of SCI metrics with these case studies at top journals in the field such as IEEE Transactions on Sustainable Computing or Journal of Sustainable Computing, which will attract attention from a broader audience.

**Comment by Henry-WattTime** [comment]
I think this is an excellent idea, but I think should be part of the followon efforts. I think we should publish this Alpha and then start building case studies. @buchananwp I think the work you've done might be a perfect example.

**Comment by jawache** [comment]
Agreed, I think @Green-Software was talking about doing this post Alpha release anyway. We'd briefly touched on this at the end of the last Standard WG call, focussing the next phase on applying the SCI to some use cases. 

I think we should take a few baby steps first, perhaps 3/4 internal case studies with **very simple** apps from a broad set of categories to demonstrate it can be applied in a variety of contexts. 

- A monolith desktop windows app
- A very simple cloud workload
- A popular open-source library (numpy? tensorflow?)
- Our own website.

The equation looks simple but getting the data is incredibly challenging, it's going to be a lot harder to calculate than we think!

**Comment by buchananwp** [comment]
That sounds great! Especially since 'E' and 'M' are readily available :)

Best,
Will
