### ISSUE TITLE
How to calculate the Energy value in the SCI formula (E)

### ISSUE THREAD

**Issue by srini1978** [Green-Software-Foundation/software_carbon_intensity#217]
Is there a way to be prescriptive around how we calculate the E in the SCI formula ?

I was looking at this article -https://greensoftware.foundation/articles/gps-up-a-better-metric-for-comparing-software-energy-efficiency and the point about Greenup is good. 

The intent of me raising this here is to understand how we can be more prescriptive about this component

**Comment by Henry-WattTime** [comment]
We leave it up to the developer/person scoring the software to determine the best way to calculate E. They should use the best available information (which may be limited in some cases) to calculate a meaningful value. 

In a case where no information is available about the hardware energy consumption, it is reasonable to make assumptions/comparisons using other hardware information. Potentially need to report assumptions to give it meaning when reporting score.
