### ISSUE TITLE
[Tool Selection] GitBook

### ISSUE THREAD

**Issue by Sealjay** [Green-Software-Foundation/software_carbon_intensity#236]
@Sealjay to deliver a demo of GitBook on an SCI fork on March 10th. FYI @jawache @seanmcilroy29 @Henry-WattTime @atg-abhishek

**Comment by atg-abhishek** [comment]
Thanks @Sealjay - really looking forward to it!

**Comment by ng-druid** [comment]
I think an important point to get across to everyone is those old Wordpress, Magento, Monolithic CMS platforms have plagued the environment. They are extremely inefficient and suck the environment dry. They are constantly on and consume many more resources than needed for the job that they do. Alternate solutions can be built that run much more efficiently based on green software design principles.

**Comment by atg-abhishek** [comment]
Closing this issue since we're using GDocs for the first pass at the case study and then submit to the [case study folder](https://github.com/Green-Software-Foundation/software_carbon_intensity/tree/dev/case-studies) once it is ready via a PR.
