### ISSUE TITLE
Farm Insights - Raspberry Pi

### ISSUE THREAD

**Issue by tmcclell** [Green-Software-Foundation/software_carbon_intensity#241]
Farm Insights - Very very simple use case. .NET Core application running with temperature, humidity, sunlight, and soil moisture sensors. Running headless on a raspberry pi. I purchased a power meter and had the pi plugged into it. Ontology is device only.

Blog post located here - https://www.wonderfultinyfarm.com/wtfblog/software-carbon-intensity

### Energy Efficiency 
.003 kWh per day for both the PI and the application running on the PI.

### Margin Location Emissions

.713kg per kWh per Henry per day.

### Embodied Carbon

Discuss Raspberry PI and no such number exists. Used 55 Kg of CO2e, used for smartphone metrics.

### (What) Software boundary

Boundary identified as hardware device and application only.

### (Scale) Functional unit 
Per Raspberry Pi

### (Quantify) SCI Value Calculation

((.003 kWh/D x 365 days/year * .713 kg/kwh)) + 55 kg

(.003 x 365) = 1.095 - kilowatts to run the device/software for 1 year

.713 x 365 days/year = 260 - location based margin emissions for 1 year

1.095 * 260 = 284.7 - kilowatts to run the software for 1 year x location based margin emissions

((kilowatts to run the software for 1 year x location based margin emissions for 1 year) + embedded carbon of the device) for each instance of the device.

**((1.095 *260) + 55 =339.7 CO2e per year**

**Comment by tmcclell** [comment]
I'll on vacation 3/13-3/18 - If possible, please wait for me to join the conversation!

**Comment by Henry-WattTime** [comment]
Hello Tammy,

I reworked your math a little to, does this make sense? 

operational                                                           + embodied                    = total/SCI score
((0.003 kWh/D x 365 days/year * 0.713 kg/kwh)) + (55 kg/3 year lifespan) = total
0.078                                                                     + 18.333                          = 19.114 kg/year of sensor suite operation

((kilowatts to run the software for 1 year x location based margin emissions rate) + (embedded carbon of the device for one year of life) for each instance of the device. In this case, I think the function unit is a year of sensor package (sensors, pi, etc) operations. 

Spreadsheet also attached if anyone wants to play with it.
[Farm Insights.xlsx](https://github.com/Green-Software-Foundation/software_carbon_intensity/files/8256511/Farm.Insights.xlsx)

**Comment by atg-abhishek** [comment]
Thanks for clarifying this further @Henry-WattTime - looking forward to the discussion this week on it!

**Comment by tmcclell** [comment]
Thanks Henry - this makes sense and I've updated the blob post. I do still have a question on whether the embodied carbon is for 3-year lifespan vs lifetime.

**Comment by tmcclell** [comment]
Closing and marking complete for Phase I. Initial boundaries were specified as the raspberry pi and software running on it. Case study completed and will reopen another for Phase 2 ontology which includes IoTHub, Storage and Power Bi additions.
