### ISSUE TITLE
[case study] TDP based estimation should be consider per chip rather than per core

### ISSUE THREAD

**Issue by YaSuenag** [Green-Software-Foundation/software_carbon_intensity#250]
[SCI Case Study for eShop](https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/dev/case-studies/eshoppen.md) estimates energy consumption using TDP and CPU utilization with following formula:

```
E = Server utilization * Number of hours * Number of cores * TDP * TDP co-efficient
```

TDP means thermal design point for computer chip or component (e.g. CPU), not for a CPU core.
https://en.wikipedia.org/wiki/Thermal_design_power

So I think we should calculate SCI with following formula.
We should measure total CPU utilization, not per core, and also we should consider CPU affinity if we set of course.

```
E = Server utilization (total CPU) * Number of hours * Number of CPUs * TDP * TDP co-efficient
```

In this case (eShop), I think we can get 0.011 Kwh as consumed energy as following:

* Server utilization = 18.3922%
* Number of hours = 1
* Number of chip = 1 (Xeon Platinum 8270 has 26 cores per chip, but the app uses 2 cores only)
* TDP = 205W
* TDP Coefficient = 0.32

```
E = Server utilization (total CPU) * Number of hours * Number of CPUs * TDP * TDP co-efficient
  = (0.18 * 1 hour * 1 CPU * 205 TDP * 0.32 TDP co-efficient)/1000
  = 0.011
```

**Comment by atg-abhishek** [comment]
Set to auto-close this issue when PR #256 is completed.

**Comment by YaSuenag** [comment]
I've commented about this in https://github.com/Green-Software-Foundation/software_carbon_intensity/pull/256#discussion_r901170395 , however it does not seem to be changed.  
I hope this issue will be fixed in #256 completely.

**Comment by YaSuenag** [comment]
I confirmed that new commit in the PR fixes this issue, so I agree to close this when the PR is merged.

**Comment by Henry-WattTime** [comment]
WG: addressed in the case study/example calc from Srini.
