### ISSUE TITLE
Question re: location-based marginal emissions

### ISSUE THREAD

**Issue by abeggchr** [Green-Software-Foundation/software_carbon_intensity#258]
The specification regarding location-based marginal carbon emissions states: 

_Location-based measures the grid carbon intensity of a regional balancing authority. From a developer perspective, only the location-based info is important for having an impact on reducing carbon emissions. This excludes market-based measures, and is distinct from 100% renewable energy claims.

The only figure that matters if you’re trying to optimize the scheduling of your compute in real-time is the marginal emissions intensity. This is the emissions intensity of the marginal power plant which will be turned up if you schedule some compute (e.g. increase electricity demand from the grid) at that moment._

Questions:

- What's the difference between a "marked-based measure" and "location-based measures"?
- To calculate the SCI, only the carbon emissions in the electricy net where the server is operated is relevant (i.e. 29g in Sweden when writing this issue according to https://app.electricitymap.org/zone/SE)?
- Now when Microsoft claims to operate a 100% renewable energy datacenter (https://azure.microsoft.com/en-us/blog/achieving-100-percent-renewable-energy-with-247-monitoring-in-microsoft-sweden/) - is this a "marked-based measure" or can the factor 0 be used for the location-based marginal carbon emissions?

**Comment by atg-abhishek** [comment]
Henry: we should have a guide for choosing a vendor
