### ISSUE TITLE
Add reference to the  SCI open data project in Specifications 1.0

### ISSUE THREAD

**Issue by srini1978** [Green-Software-Foundation/software_carbon_intensity#262]
In the introduction section where we have the following paragraph "The SCI encourages calculation using granular real-world data, which is challenging to obtain in some of these environments, particularly the public cloud. The Green Software Foundation is committed to ensuring everyone has free and open access to the data sources required to calculate the SCI at lower resolutions and will provide tools and guidance for getting this information wherever systems are hosted" , should we have a reference to how the group should work with the SCI open data group when data is not readily available. 

@jawache  I believe you have some point of view here?

**Comment by srini1978** [comment]
Modified the specification and created the pull request https://github.com/Green-Software-Foundation/software_carbon_intensity/pull/265

**Comment by atg-abhishek** [comment]
Set to auto-close this issue once PR #265 is completed.

**Comment by Henry-WattTime** [comment]
Closed with PR #265
