### ISSUE TITLE
Quantification method -Guidance regarding methodology recommended for usage energy calculations - Specifications 1.0

### ISSUE THREAD

**Issue by srini1978** [Green-Software-Foundation/software_carbon_intensity#264]
Today, the specifications just calls out if we need to either a) Calculate using real world data or b) Model . However the actual energy calculation approach could be either a) Done by attaching RAPL or energy meters to all the components in the software boundary or b) Use approximation models or reference models and then do calculation. 

For example, for the server component in the case study, we used the TDP approach and converted the CPU utilization into TDP co-efficient. Boavizta organization and Teads engineering took the approach of doing calculation with on-premise servers using meters and then mapping them to AWS servers.

Do we want to talk about or give guidance on the recommended approach based on the learnings so far?  My approach would :While TDP based approach we need further research to firm up this approach. We need to brainstorm some more details around how we can refine the TDP based approach.

**Comment by Henry-WattTime** [comment]
Ziliang: instrumentation to measure supercomputers in high performance computation. Strict measurement requirements to make data center energy consumption more comparable. More heterogenous devices we are dealing with, so less ability to be strict. More relaxed at this point. We could propose a model.  
Asim: agree to keep loose to begin with. Spec shouldn't _tell_ you how, but GSF should help you figure out how to calculate it. Part of training? Part of Open Data Project? in ancillary
Srini: In case study, quantification/calculation methodology is explicitly explained. Had to explain approach to people asking. 

Consensus: Spec not include strict energy calculation guidance, but GSF ancillary documents should help you figure out how to calculate this. No PR at this time.
