### ISSUE TITLE
Taking into account energy consumption of ancillary equipment into the SCI score

### ISSUE THREAD

**Issue by GadhuNTTDATA** [Green-Software-Foundation/software_carbon_intensity#266]
For Data Centers a significant consumer of energy are Data Center cooling systems. Its quite possible for cooling systems to use as much or even more energy than the hardware that it supports. Should this factor be taken into account in the SCI score. 

Widely accepted benchmarking standards such as PUE already exist for data centers. 

PUE(Power Usage Efficiency)  = Power used by the total facility/Power used by the IT equipment

Should we take this into account in the SCI Score? I feel this can be an important choice that I can make as software developer since my score will differ considerably if I choose to host my application in a data center with a high PUE.

**Comment by Henry-WattTime** [comment]
Henry: supports including this
Asim: E should already take this into account. 
Proposed
"If your boundary includes on-premise and/or cloud data center operation, E should take into account the efficiency of the data center, including cooling and other energy consumption necessary to operate a data center. This is often described as Power Use Efficiency (PUE)."

Gadhu, would you be willing to add this to the to the spec?

**Comment by atg-abhishek** [comment]
Linked to PR to auto-close this issue once that PR is approved.
