### ISSUE TITLE
Adding "End user Devices" to the list of "Supporting infrastructure and systems MAY include" in the Software Boundary section

### ISSUE THREAD

**Issue by bninassi** [Green-Software-Foundation/software_carbon_intensity#267]
The current list of examples may suggest that the impact of end user devices is not to be included in the SCI computation, yet in the case of a web platform it is probably the most important source of emissions when you scales up.

**Comment by Henry-WattTime** [comment]
WG discussion
Asim: are there other terms that encompass other types of devices? (Televisions, laptops, iot, EVs, edge devices)
Pindy: Standard term? 
Henry: standard term, define in definitions? 

Action: Benjamin, please create PR for this item in the list.
-End user devices
-IoT devices
-Edge devices

**Comment by bninassi** [comment]
PR created https://github.com/Green-Software-Foundation/software_carbon_intensity/pull/269

**Comment by atg-abhishek** [comment]
Linked to PR #269 to auto-close this issue when PR is approved.
