### ISSUE TITLE
Add details for Embodied Emissions (M)

### ISSUE THREAD

**Issue by navveenb** [Green-Software-Foundation/software_carbon_intensity#268]
For Embodied Emissions (M),  there is always a question around how can you get the data.
It would be good to add a link to SCI open data as part of the specification.
Can we add more examples, probably for cloud measurements. 

Secondly Total resource of RR/TR, it’s difficult to calculate for cloud VMs. All these details are abstracted by the cloud vendors.Some guidance should be provided for that.

**Comment by atg-abhishek** [comment]
Would this again be something that we do as a part of guidelines / appendix associated with the SCI rather than making direct edits to include into the spec @navveenb ?

**Comment by Henry-WattTime** [comment]
Addressed as part of FAQ. 
Potential area for new project to strengthen guidance. Collect the data, see what is available, translate for users.
