### ISSUE TITLE
Your SCI score is composed of other SCI scores

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/software_carbon_intensity#270]
### Discussed in https://github.com/Green-Software-Foundation/software_carbon_intensity/discussions/235

<div type='discussions-op-text'>

<sup>Originally posted by **jawache** March  3, 2022</sup>
Some components in your software boundary will be components **you manage**, for these you will need to calculate an SCI score from the ground up, quantifying `E`, `I` and `M`.

Some components in your software boundary will be components **managed by others** and provided as a service. These may either have calculated and published their own SCI scores which you can simply add into your own aggregate SCI score. Or the SCI Data project may have calculated a generalised SCI score for that type of service, e.g. networking.

For example say your software boundary is:

- Servers which **you** manage.
- Database **managed by another organisation** which has calculated and published an SCI score of 2.3 g/MB stored.
- Networking **managed by others** for which the SCI Data project has published a generalised score of 10g/GB transferred.

You applications total SCI score will be the sum of 

1. SCI score of your servers.
2. SCI score of your database.
3. SCI score of you networking.

- For (1) you quantify the SCI score from the ground up by quantifying the `E`, `I` and `M`
- For (2) + (3) you leverage previously calculated SCI score and just translate them to this SCI scores `R`.

Let's say the R is `User` and we have modelled that a single `User` stored 20MB of data and transfers 2GB of data.

1. `SERVER SCI = (E + I) + M per User`
2. `DATABASE SCI = (2.3 * 20)g per User`
3. `NETWORKING SCI = (10 * 2)g per User`

(2) + (3) are just scaled so the denominator, the `R`, is the same across all. That way all the components can be summed up into one total.

Eventually, in the far future, **every service** will have an SCI score all published to the GSF via the SCI Reporting project. So theoretically calculating your applications SCI score will become easier and easier as more and more of it's dependant components will have calculated their own SCI score which you can leverage.</div>

**Comment by atg-abhishek** [comment]
@jawache have you made a PR for this? If so, please feel free to link it to this issue so that it will be resolved and closed once that PR is approved. Thanks!

**Comment by hayasri** [comment]
Hi Folks, 

Adding a comment here on the recommendation from Chris Adams. We are a three person startup building this type of SCI scoring for Kubernetes. We'd love to get involved in building the tooling for SCI scores of cloud services. Hoping to get in touch with the right folks! 

Regards
Haya

**Comment by Henry-WattTime** [comment]
Closed with #286
