### ISSUE TITLE
Add more context on SCI for software professionals 

### ISSUE THREAD

**Issue by navveenb** [Green-Software-Foundation/software_carbon_intensity#272]
Adding few sentences on how SCI can be applied for various software roles would be helpful. May be this can be added to introduction or a new section can be added - 

The SCI is for everyone. For instance something that connects with all software professionals, what role they play and talk about reduction of SCI score -

For a software developer reducing the SCI score would imply writing energy efficient code
For devOps, it would be about creating carbon-aware pipeline, when to schedule builds and leverage clean energy 
For AI/ML, its about training model optimization and leveraging optimized hardwares
For Testing, it would imply …
For Architect, it would imply ..

**Comment by atg-abhishek** [comment]
I like this suggestion @navveenb, can you create a PR against this issue that the WG can review? Thanks!

**Comment by seanmcilroy29** [comment]
Navveen to create a PR

**Comment by Henry-WattTime** [comment]
Closed with #285
