### ISSUE TITLE
Request for corrections in section "Methodology Summary"

### ISSUE THREAD

**Issue by varnepalli1** [Green-Software-Foundation/software_carbon_intensity#277]
Below wording looks to me not clear, based on the introduction. 

**The Software Carbon Intensity (SCI) is a rate, carbon emissions per one unit of R**

Should it be ...measuring rate of carbon emission per unit....??

**Comment by atg-abhishek** [comment]
No, please see the definition of what R is [here](https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/dev/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md#functional-unit-r) to understand what we're referring to.
