### ISSUE TITLE
Rephrase SCI formula for better clarity and understanding

### ISSUE THREAD

**Issue by varnepalli1** [Green-Software-Foundation/software_carbon_intensity#278]
Current snippet:
Please see my comments inline
--------

SCI = ((E * I) + M) per R. 
[Vasu]: SCI is an abbreviation in our doc context. So, we are referring it as an attribute (LHS) here. I would say, it we could use 'C' directly here instead of SCI. If we keep both SCI and C, C looks like an alias to SCI and SCI we are using in two contexts, which is confusing

[Vasu]: It would be more clear if we mention the formula and attributes expansion from higher to low level expansion. for example, if we say something like
C = O +M
Then explain and expand O and M and their respective low-level formulae down.

Where:

    E = Energy consumed by a software system

    I= Location-based marginal carbon emissions

    M = Embodied emissions of a software system

    R = Functional unit (e.g. carbon per additional user, API-call, ML job, etc)

The equation can be further refined to

SCI = (O + M) per R

Where:

    O = E * I = Operational emissions based on energy consumption (E) and location-based carbon intensity measurement (I)

And once more this can be further refined into:

SCI = C per R

Where:

    C = O + M = Amount of carbon the software is emitting.
-----------

**Comment by atg-abhishek** [comment]
@varnepalli1 just as a note since you've raised a few issues on our repo, please use the correct labelling. The `case-study-submission` tag is only meant to be used when you're creating a case study submission. 

As for your in-line comments here, we appreciate it and will consider if this is something that WG feels needs to be changed. Thanks!
