### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by FinancialPenguin** [Green-Software-Foundation/software_carbon_intensity#280]
''invlved'' should say involved
https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/1b4804f58e18dbee052897f8ea42c7e2669593ff/README.md?plain=1#L22

**Comment by atg-abhishek** [comment]
Thank you @FinancialPenguin for pointing it out. PR #282 addresses this and will auto-close this issue once approved.
