### ISSUE TITLE
[Action Item] Move SCI-Data from Opensource WG to the Standards WG

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/software_carbon_intensity#293]
Move SCI-Data from Opensource WG to the Standards WG

- Inform project leads of the proposal
- Make a motion in the Opensource to move the project

**Comment by atg-abhishek** [comment]
@seanmcilroy29 is this going to be discussed today? https://github.com/Green-Software-Foundation/standards_wg/blob/main/Agenda_Minutes/2022.09.08.Agenda.md

**Comment by seanmcilroy29** [comment]
SCI Data now with SWG
