### ISSUE TITLE
[Action Item] Creation of support pages for docusaurus

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/software_carbon_intensity#294]
Creation of support pages and structure for Docusaurus pages

- [ ] FAQ
- [ ] Guidance 
- [ ] Demo's
- [ ] On boarding guide

**Comment by atg-abhishek** [comment]
Is the onboarding guide for the onboarding to use the SCI or to participate in the SWG at the GSF?

**Comment by seanmcilroy29** [comment]
Pages up and running
