### ISSUE TITLE
[Consistency Review submission] Remove 'Version Alpha' section

### ISSUE THREAD

**Issue by Henry-WattTime** [Green-Software-Foundation/software_carbon_intensity#311]
# Consistency Review Submission

## Comment

How should we re-write this section with the new 1.0 version of the spec?
(https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/dev/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md#version-alpha)

**Comment by atg-abhishek** [comment]
Agreed @Henry-WattTime - we can create a PR that targets this issue to address this section of the SCI

**Comment by Henry-WattTime** [comment]
WG: consensus, that this will be turned into a PR. @atg-abhishek to make this revision.
