### ISSUE TITLE
[Consistency Review submission] Is there really a reporting requirement? 

### ISSUE THREAD

**Issue by Henry-WattTime** [Green-Software-Foundation/software_carbon_intensity#312]
# Consistency Review Submission

## Comment
https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/dev/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md#procedure
"Report. The SCI has standards for reporting that must be met, including a disclosure of the software boundary and the calculation methodology."

**Comment by atg-abhishek** [comment]
@Henry-WattTime should we soften the language that there _will be_ some reporting standards that users of the SCI will have to adhere to once it is released?

**Comment by Sealjay** [comment]
I definitely think there _should_ be a reporting requirement. That said, the baseline list is broken in https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/dev/Software_Carbon_Intensity/Appendix_A_Further_Information_on_Reporting_Requirements.md :)

**Comment by Henry-WattTime** [comment]
WG: for now, this a 'should' reporting requirement makes sense, will move to a 'shall' in the future as we refine reporting requirements. @Henry-WattTime will make the modification to the text to reflect.

**Comment by Sealjay** [comment]
Moved to SCI reporting project - https://github.com/Green-Software-Foundation/sci-reporting/tree/main @Henry-WattTime
