### ISSUE TITLE
[Consistency Review submission] Change order of embodied emissions calculation

### ISSUE THREAD

**Issue by Henry-WattTime** [Green-Software-Foundation/software_carbon_intensity#314]
# Consistency Review Submission

## Comment
Should the formulas in the embodied emissions section be inverted to match the complexity hierarchy (simple first, break out each term into its constituent parts)
(https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/dev/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md#embodied-emissions-m)

**Comment by atg-abhishek** [comment]
That's a good callout @Henry-WattTime - this will then make it not only easier to read but also consistent with how we've chosen to reorder the core formula at the top-level for the SCI.

**Comment by Henry-WattTime** [comment]
WG: Approved, @Henry-WattTime to make the pull request.

**Comment by Henry-WattTime** [comment]
addressed in #320
