### ISSUE TITLE
[Consistency Review submission] Remove Definition Section? 

### ISSUE THREAD

**Issue by Henry-WattTime** [Green-Software-Foundation/software_carbon_intensity#316]
# Consistency Review Submission

## Comment
The definition section seems vestigial and underdeveloped. Should we just omit overall? We generally define terms in-line.

https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/dev/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md#definitions

**Comment by atg-abhishek** [comment]
@Henry-WattTime I think it would be good to expand the definition a little bit more - any suggestions on which aspects you think are missing?

**Comment by Henry-WattTime** [comment]
WG:
Separate dictionary is a better way to manage definitions.
Can remove definitions, link to other dictionary in section. 
@atg-abhishek to make PR.

**Comment by Henry-WattTime** [comment]
Addressed in #318
