### ISSUE TITLE
[Consistency Review submission] 404 links/bug for R baselines

### ISSUE THREAD

**Issue by Sealjay** [Green-Software-Foundation/software_carbon_intensity#317]
# Consistency Review Submission

## Comment

- Running a training course on the SCI at the moment - and getting people in the habit of creating an SCI report to bundle with their software.

-I noticed we refer to baseline in the spec, but there are no longer pre-named baselines:
https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/dev/Software_Carbon_Intensity/Appendix_A_Further_Information_on_Reporting_Requirements.md

<img width="715" alt="image" src="https://user-images.githubusercontent.com/19361656/191789226-86ee3ab4-7458-4d6a-a881-ea86e0440454.png">

So the R-source URL is now broken.

**Comment by Henry-WattTime** [comment]
WG: this issue will be resolved by moving to reporting project. No action for spec.
