### ISSUE TITLE
Disambiguate 'Marginal' 

### ISSUE THREAD

**Issue by buchananwp** [Green-Software-Foundation/software_carbon_intensity#33]
We'll need to update the SCI on terms & methodology

- Currently, we have 'R' which is a baseline, also represneting 'marginal' (R)
- We've also got 'location-based marginal carbon intensity (I)

**Comment by atg-abhishek** [comment]
@buchananwp thank you for pointing that out. In addition, I've added the `dictionary` tag since these are terms that need to be inserted in there as well in case you'd like to take a stab at them?

**Comment by jawache** [comment]
I've only seen this in reference to `I` and not `R`. Is this issue more about adding a definition of "Marginal" somewhere in our spec, dictionary etc...?

**Comment by atg-abhishek** [comment]
Closing since this has now been addressed and can be resurfaced if during the review of the spec any inconsistencies are revealed.
