### ISSUE TITLE
Terminology: "Carbon emission" or "greenhouse gas (GHG) emission"?

### ISSUE THREAD

**Issue by patricekrakow** [Green-Software-Foundation/software_carbon_intensity#338]
Should you/we not replace the terms "carbon emission" by "greenhouse gas (GHG) emission"? For instance,

> This specification defines a methodology for calculating the rate of carbon emissions for a software system.

could/should be replaced by

> This specification defines a methodology for calculating the rate of greenhouse gas for a software system. 

It would be more consistent with the usage of "CO2 equivalent" in units of measure.

**Comment by atg-abhishek** [comment]
That's a great point and certainly worth discussing @patricekrakow! @seanmcilroy29 we can add to the next meeting agenda? 

In the meantime, thoughts on this @jawache @Henry-WattTime ?
