### ISSUE TITLE
Standardize Units For SCI

### ISSUE THREAD

**Issue by buchananwp** [Green-Software-Foundation/software_carbon_intensity#36]
Propose we standardize around units for reporting & methodology (e.g Joules/kWh/ (gCO2eq/kWh)) 

The carbon intensity of electricity is a measure of how much carbon (CO2eq) emissions are produced per kilowatt-hour (kWh) of electricity consumed, for a standard unit of gCO2eq/kWh. 

Let's use a good _metric_ measurement if possible! 

Some immediate thoughts: 

- Energy (Joules? kWh?)
- Location-based carbon intensity MOER (I) 
- Embodied carbon (kg? g? lbs?)

@Henry-WattTime last time I dug into WattTime's documentation, it was really hard to find units within WattTime's documentation around carbon. I think I did't find a clear delineation between kg and lbs.  Is this something you can add to WattTime's documentation help surface?

**Comment by atg-abhishek** [comment]
Thanks for bringing this up @buchananwp - I think the more `international` units we use the better, i.e. avoiding the use of lbs and other non-metric units would be preferable to gain global traction. 

Also, @buchananwp can you make a separate issue for defining MOER for the GSF Dictionary? Thanks!

**Comment by atg-abhishek** [comment]
g CO2/kWh seems to be the most comfortable unit for everyone, and Will points out that we can use scientific notation as we need larger numbers. 

@jawache will include this in a PR
