### ISSUE TITLE
Defining Baselines (`R`)

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/software_carbon_intensity#37]
In today's WG meeting we discussed defining possible definitions of R, being the baseline as a denominator.  This issue is to create a thread and discussion to capture this.

Some items discussed for example:
* per user
* per workstation
* per install
* per $

We also discussed creating a "Recommended baselines" or "Accepted baselines" and a "Not accepted baselines".  

I will leave it there for now so we can discuss.

**Comment by jawache** [comment]
@atg-abhishek I changed this issue from `problem-definition` to `requirements-constraints` (I think I must have uber perms in the GH org!) I see this as a discussion about the boundaries of the selection of `R` in the equation.

The challenge is this. If we are too prescriptive in the list of allowed `R` then we risk alienating people and use cases that need a broader definition. If we leave it as a free-form choice then this makes it harder to make comparisons as each software in the world can choose a different R and none of them can be compared. Maybe the second point isn't even important?

We *could*  say "you SHOULD use one of our preset lists for `R` but if none of those would you can choose another but you MUST say why in your report" that might be a happy medium. But again, I'm totally on the fence in this one I could go either way.

**Comment by atg-abhishek** [comment]
@jawache maybe I can move this into the SCI value reporting PR #73 that I've created, thoughts?
