### ISSUE TITLE
Baseline: Do we expose (`C`) AND (`CI`)? 

### ISSUE THREAD

**Issue by buchananwp** [Green-Software-Foundation/software_carbon_intensity#38]
C = total carbon emissions per piece of software
CI = carbon emissions per unit baseline

This is a root issue per @Henry-WattTime. Some open questions around: 

- What do we do if only one piece is available? 
- What if C goes up, but CI goes own?

**Comment by jawache** [comment]
This is where we can perhaps introduce the SHALL and SHOULD concepts.

SHALL is mandatory to implement the spec, if you want to be certified, you have to meet all the SHALLs.

SHOULD is a guideline, we recommend you do this but if you don't you can still say you are adhering to the SCI.

So it's possible to say, "you SHALL calculate and report your `CI` number. If it's possible for you to do so then you SHOULD also calculate and report your `C`".

The challenge with reporting `C` is that I would argue most products will not be able to calculate it anyway. E.g. python, or any open-source product or any mobile app or any app that doesn't want to report back potentially private data like user GPS locations to a central server. 

On another level sometimes revealing your `C` and `CI` together might reveal competative details about your infra or products so if we insist on publishing `C`, even though there is a will to calculate it they will not be able to report it publically for fear of revealing competitive info. This pops up *A LOT* in conversations, customers have to sign NDAs with _some_ cloud providers before they give them detailed information about their specific energy consumption/carbon emissions.

**Comment by SaraEmilyBergman** [comment]
I agree with your point Asim, I see how reporting `C` can be hard for many. But I still want to say that by only enforcing `CI` to be reported, we are potentially opening up for people make their number look better than they are. It is possible to artificially inflate the baseline unit, by changing your implementation, without affecting `C` much, but making it look like `CI` has improved.

This get's extra tricky when we think about the scope of software. Let's say network emissions are not in scope for `C`, so I make a change to my software which requires more calls over the network, to fetch a smaller payload more often for example. This might mean I move, or even add, real emissions to the network and client device, but not really changing `C` and in fact increasing the base unit => `CI` goes down.

It is not likely the biggest problem and I guess at some point we'll just gonna have to assume good intentions :)

**Comment by atg-abhishek** [comment]
So we can start with saying that you MUST report the `CI` and you SHOULD report the `C` but if you can't report the `C` you MUST provide a reason for why not (business secrets are a legitimate reason)

**Comment by atg-abhishek** [comment]
we discussed the possibility of ratcheting up requirements over time
