### ISSUE TITLE
What is the market perspective for this specification?

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/software_carbon_intensity#4]
From a market perspective...  

* What can you do with this specification?
* What problem does this solve?
* How can this specification be applied?
* Consider the target audience and provide deployment examples as possible.

[This was taken from the template spec doc]

**Comment by atg-abhishek** [comment]
@jawache 

1. I think the purpose of this specification will be to enable standardization across industry empowering customers to make more informed choices in the software solutions that they pick. 
2. This solves the problem of incompatible and opaque metrics that are _potentially_ gameable today making it difficult for the end-consumer to make a choice that is aligned with what they are looking for in terms of meeting their environmental goals when purchasing / using software solutions. 
3. The application of the specification can be towards creating a _certified, standardized, practical_ score to the **entire** software solution. 
4. The target audience for this are software architects, developers and maintainers who ideally can use this as a tool where they can enter characterisitics about their software solution and get a score that they can share with their customers highlighting the environmental impact of their solution

**Comment by jawache** [comment]
I really like these answers, @atg-abhishek  would you consider creating a PR to add these to the spec?

**Comment by atg-abhishek** [comment]
Yes for sure! Happy to @jawache! Will get to it later in the week though 😊

**Comment by Henry-WattTime** [comment]
from Dan: benchmark so that you can compare your software against other software to see how it is doing

**Comment by atg-abhishek** [comment]
Incorporated through PR #16
