### ISSUE TITLE
Review LF build tools and provide recommendations

### ISSUE THREAD

**Issue by Sealjay** [Green-Software-Foundation/software_carbon_intensity#48]
Following #39 - identify LF build tools, and requirements we need to adhere to, including:

- Folder structure
- Templating requirements
- Deployment - GH actions, CICD, basis of the tech

Provide recommendations

**Comment by atg-abhishek** [comment]
@Sealjay @seanmcilroy29 do we want to keep this issue open? Maybe we can combine this and #64, #83 all under one place?

**Comment by Sealjay** [comment]
Lets merge into one @atg-abhishek  - this one seems the most all encompassing?

**Comment by atg-abhishek** [comment]
Sounds good @Sealjay - I've closed them and left a comment indicating that all discussions on that can be carried out here for ease of tracking and implementation. Thanks!

**Comment by seanmcilroy29** [comment]
@Sealjay - once you set this up in your repo, could we have a call to review the flow process, as only the Working Group Chair(s) can merge agreed PRs.

**Comment by Sealjay** [comment]
Sounds good @seanmcilroy29!
I've created #98 which has the notify for new users, and invite to contribute, doesn't yet include RNA auto merging, but I've mapped the process out, so we can set up a call.
I've got some points to clarify as well with @atg-abhishek : what labels do we need to monitor for RNA, and which email address needs to receive the notification.

**Comment by Sealjay** [comment]
Right, I think I've configured an auto-merge process too, so I'll arrange a call @seanmcilroy29

**Comment by atg-abhishek** [comment]
@Sealjay can we close this issue?

**Comment by atg-abhishek** [comment]
@seanmcilroy29 I'm closing this issue, I don't think anything else is needed here, we can reopen if actions are needed.
