### ISSUE TITLE
Defining software boundaries

### ISSUE THREAD

**Issue by atg-abhishek** [Green-Software-Foundation/software_carbon_intensity#56]
For anybody using the SCI, we should provide a set of software boundaries for different types of applications.

**Comment by Henry-WattTime** [comment]
Supporting infrastructure may include: (Compute, Storage, Networking, Memory, Monitoring, Idle Machines)

**Comment by atg-abhishek** [comment]
Sarah Hsu had mentioned that monitoring frequency could be reduced as a part of the impact of the supporting infrastructure

**Comment by vaughanknight** [comment]
Some notes for discussion later this week so I don't forget.  

Monitoring, logging, scanning, testing, operations, backup, and other supporting infrastructure and systems.

**Comment by navveenb** [comment]
We can define like supporting infrastructure (network, edge, storage, monitoring, logs ..) + runtime + idle/avg consumption (based on server/hardware types)
