### ISSUE TITLE
Approved PRs should automatically merge

### ISSUE THREAD

**Issue by buchananwp** [Green-Software-Foundation/software_carbon_intensity#64]
@Sealjay suggested approved PRs should merge automatically after a few days, which will bypass permissions issues.

**Comment by atg-abhishek** [comment]
So @buchananwp @Sealjay that is possible through the R&A process. We just need to tag the PR after it has been approved with one of the R&A tags and then we can follow that process. cc @Henry-WattTime does that square with what we had discussed as well?

**Comment by Sealjay** [comment]
Is there a way to unlock labels so that we can apply an R&A tag, or request that to be done?

**Comment by atg-abhishek** [comment]
@Sealjay yes we are now going to start using the R&A labels - they've been created in the Dictionary and SCI repos. As for whether they can be "unlocked", that is a question for @seanmcilroy29. For the time being you can take a look through the available labels and tag me in the comment and I can apply the appropriate label for you. In the available labels, you will notice a number after the `-` which indicates the number of days for which the PR will be kept in the review phase after which it will be closed out and approved for merge. This can happen async ridding us of the need to have to wait for the weekly meeting before the PR can be reviewed and approved.

**Comment by atg-abhishek** [comment]
@seanmcilroy29 question for you: is there a way (through GH Actions or otherwise) that when we apply those specific labels that I'm talking about (the ones that have a `-` in their name with a number) that it triggers a notification to our `standards-wg` mailing list that an item has entered the R&A phase and then it closes inputs based after a set time as determined by the number in that tag?

**Comment by Sealjay** [comment]
There are github actions to auto-merge, and then github actions to send emails to the mailing list.

- Email when a label is applied: https://github.com/marketplace/actions/issue-label-notifier
- See how long a label has been applied: https://github.com/marketplace/actions/label-timer
- Add a label after 7 days (or whatever the RNA period is)
- Auto-merge pull request when label is applied: https://github.com/marketplace/actions/auto-merge-pull-request

**Comment by atg-abhishek** [comment]
Sweet!! This is awesome @Sealjay  - thank you so much for investigating this!

**Comment by atg-abhishek** [comment]
Maybe there's some useful stuff here too? https://github.com/sdras/awesome-actions

**Comment by atg-abhishek** [comment]
@seanmcilroy29 any updates on if any of these worked? Thanks!

**Comment by Sealjay** [comment]
@seanmcilroy29 @atg-abhishek  - do you want me to set this up on my own repo to test it out, then create a pull request? I'm happy to configure.

**Comment by atg-abhishek** [comment]
Sounds good to me if that is part of the approved workflow @seanmcilroy29 ?

**Comment by atg-abhishek** [comment]
Consolidating all discussions under #48  and closing this one
